# Generated by Django 2.1.5 on 2019-02-23 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='agend',
            new_name='agenda',
        ),
    ]
