# Generated by Django 2.1.5 on 2019-02-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20190223_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meetingtitle',
            new_name='meetingtittle',
        ),
    ]
